### ISSUE TITLE
[Proposal] Wallet store should be encrypted with pass phrase

### ISSUE THREAD

**Issue by zocoi** [kardiachain/kardia-explorer-frontend#168]
This is a minor security proposal. Wallet store and private key can be accessed without pass phrase in `localStorage`. For unattended laptop, attacker can inspect the website and base64 decode the wallet store to access private key without knowing the pass phrase.

<img width="1640" alt="Screen Shot 2021-04-05 at 12 24 37 PM" src="https://user-images.githubusercontent.com/212200/113617249-ffc6f380-960a-11eb-8dc6-96e362fedd4b.png">

Suggestion: Encrypt/decrypt wallet storage with pass phrase, the wallet creates and asks for pass phrase on every browser instance anyway. Example library: https://www.npmjs.com/package/secure-web-storage

**Comment by phidangnguyen** [comment]
Hi @zocoi, thanks for your proposal. Rest assured, your private key had been encrypted by the algorithm and only able to decrypt while entering the correct passcode. For each session, users have to input their passcode and use pk/seeds only on-memory sessions. It works like Metamask password but on local browser storage.

**Comment by zocoi** [comment]
Thanks, confirmed with 2 hooks `getPkByPassword` and `useWalletStorage`  in https://github.com/kardiachain/kardia-explorer-frontend/blob/master/src/service/wallet.ts

**Comment by zocoi** [comment]
Closed as resolved
